<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Contracts\Services\**" />
    <EmbeddedResource Remove="Contracts\Services\**" />
    <None Remove="Contracts\Services\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Contracts\" />
    <Folder Include="CQRS\Authors\Queries\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="13.1.0" />
    <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="11.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BookCafe.Domain\BookCafe.Domain.csproj" />
  </ItemGroup>

</Project>
